# Generated by Django 5.2.6 on 2025-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Digite seu nome de usuario", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Digite seu email", max_length=254),
                ),
                (
                    "senha",
                    models.CharField(help_text="Digite sua senha", max_length=50),
                ),
                (
                    "foto_de_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_receitas/usuarios/static/img/usuarios",
                    ),
                ),
            ],
        ),
    ]
