# Generated by Django 5.2.6 on 2025-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_managers_remove_usuario_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto_de_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="usuarios/img"),
        ),
    ]
