# Generated by Django 5.2.6 on 2025-09-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Digite seu nome de usuário", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Digite seu email", max_length=254),
                ),
                (
                    "senha",
                    models.CharField(help_text="Digite sua senha", max_length=50),
                ),
                (
                    "foto_de_perfil",
                    models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "titulo",
                    models.CharField(
                        help_text="Digite o título da receita", max_length=200
                    ),
                ),
                ("ingredientes", models.TextField(help_text="Liste os ingredientes")),
                (
                    "modo_de_preparo",
                    models.TextField(help_text="Descreva o modo de preparo"),
                ),
                (
                    "tempo_de_preparo",
                    models.IntegerField(help_text="Tempo de preparo em minutos"),
                ),
                (
                    "porcoes",
                    models.IntegerField(
                        help_text="Numero de porções/ Quantas pessoas serve"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoria da receita (ex: sobremesa, prato principal, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "foto_da_receita",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_receitas/"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receitas",
                        to="receitas.usuario",
                    ),
                ),
            ],
        ),
    ]
