# Generated by Django 5.2.6 on 2025-09-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receitas",
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="receita",
            name="visibilidade",
            field=models.CharField(
                choices=[("pub", "Pub"), ("priv", "Priv")],
                default="Priv",
                help_text="Defina se a receita é pública ou privada (Pub ou Priv)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="foto_da_receita",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_receitas/receitas/static/img/receitas",
            ),
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
