# Generated by Django 5.2.6 on 2025-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_alter_receita_autor_receita_visibilidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="foto_da_receita",
            field=models.ImageField(
                blank=True, null=True, upload_to="receitas/static/img/receitas"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="visibilidade",
            field=models.CharField(
                choices=[("pub", "Pub"), ("priv", "Priv")],
                default="Pub",
                help_text="Defina se a receita é pública ou privada (Pub ou Priv)",
                max_length=10,
            ),
        ),
    ]
