# Generated by Django 5.2.6 on 2025-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0005_alter_receita_foto_da_receita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="foto_da_receita",
            field=models.ImageField(blank=True, null=True, upload_to="img/receitas"),
        ),
    ]
