# Generated by Django 5.2.6 on 2025-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0007_alter_receita_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="foto_da_receita",
            field=models.ImageField(blank=True, null=True, upload_to="receitas/img"),
        ),
    ]
