# Generated by Django 5.2.6 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0008_alter_receita_foto_da_receita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="porcoes",
            field=models.IntegerField(
                help_text="Numero de porcoes/ Quantas pessoas serve"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="titulo",
            field=models.CharField(
                help_text="Digite o titulo da receita", max_length=200
            ),
        ),
    ]
