# Generated by Django 5.2.8 on 2025-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0009_alter_receita_porcoes_alter_receita_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("bolos", "Bolos e tortas doces"),
                    ("carnes", "Carnes"),
                    ("aves", "Aves"),
                    ("peixes", "Peixes e frutos do mar"),
                    ("saladas", "Saladas, molhos e acompanhamentos"),
                    ("sopas", "Sopas"),
                    ("massas", "Massas"),
                    ("bebidas", "Bebidas"),
                    ("doces", "Doces e sobremesas"),
                    ("lanches", "Lanches"),
                    ("saudavel", "Alimentação saudável"),
                    ("unico", "Prato único"),
                    ("outro", "Outro"),
                ],
                default="outro",
                help_text="Categoria da receita",
                max_length=100,
            ),
        ),
    ]
